version: '2'
services:
    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
            - ~/airflow/instance:/instance
        ports:
            - "8080:8080"
        command: webserver

    scheduler:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        command: scheduler

    worker:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
            - /data:/data
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        ports:
            - "8793:8793"
        command: worker
