version: '2'
services:
    redis:
        image: redis:3.2.7
        restart: always

    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=redis://@redis:6379/1
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
            - ~/airflow/instance:/instance
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - redis
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=redis://@redis:6379/1
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=redis://@redis:6379/1
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
        command: scheduler

    worker:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
            - /data:/data
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=redis://@redis:6379/1
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
        ports:
            - "8793:8793"
        command: worker
