version: '2'
services:
    redis:
        image: redis:3.2.7
        restart: always

    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: scheduler

    worker:
        image: gghez/docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ~/airflow/dags:/usr/local/airflow/dags
            - ~/airflow/requirements.txt:/requirements.txt
            - /data:/data
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        ports:
            - "8793:8793"
        command: worker
